-----------------------------------------
-- DATABASE EXPLORATION
-----------------------------------------
-- Explore All objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-----------------------------------------
-- DIMENSION EXPLORATION
-----------------------------------------
--|`dim.customers`|
-- Explore Countries our cutomers come from
SELECT DISTINCT COUNTRY FROM gold.dim_customers; 

-- Explore Marital status of our cutomers come from
SELECT DISTINCT marital_status FROM gold.dim_customers; 

-- Explore Genders of our cutomers come from
SELECT DISTINCT gender FROM gold.dim_customers; 

--|`dim.product`|
-- Explore All Categories "The Major Divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_product
ORDER BY 1,2,3;


-----------------------------------------
-- DATE EXPLORATION
-----------------------------------------
-- Find the date of the first and last order
-- How many months of sales available (timespan by Date difference of earliest and oldest order)
SELECT 
	MIN(order_date) AS first_order, 
	MAX(order_date) AS last_order,
	DATEDIFF(month, MIN(order_date),MAX(order_date)) AS 'Timespan(months)'--timespan
FROM gold.fact_sales

-- Find youngest and oldest customer ages
SELECT
	MAX(birth_date) youngest_birthdate,
	DATEDIFF(year, MAX(birth_date), GETDATE()) youngest_age,
	MIN(birth_date) oldest_birthdate,
	DATEDIFF(year, MIN(birth_date), GETDATE()) oldest_age
FROM gold.dim_customers


-----------------------------------------
-- MEASURE EXPLORATION
-----------------------------------------
-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;

-- How many items are sold
SELECT SUM(quantity) AS sold_items FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS average_price FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS ordered_items FROM gold.fact_sales;

-- Find the Total number of Products
SELECT COUNT( product_key) AS ordered_items FROM gold.dim_product;

-- Find the Total number of Customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the Total number of customers that has placed an Order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

-- Generate report that gives all this Key Metrics of the business at once
SELECT 'Total_Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' AS measure_name, COUNT( product_key) AS measure_value FROM gold.dim_product
UNION ALL
SELECT 'Total Nr. Customers' AS measure_name, COUNT(customer_key) AS measure_values FROM gold.dim_customers
UNION ALL
SELECT 'Customers with Orders' AS measure_name, COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales


-----------------------------------------
-- MAGNITUDE ANALYSIS
-----------------------------------------
-- Find Total customers by countries
SELECT 
	country, 
	COUNT(customer_key) 'Number'
FROM gold.dim_customers
GROUP BY country
ORDER BY 2 DESC;

-- Find Total Customers by gender
SELECT 
	gender, 
	COUNT(customer_key) 'total_customers'
FROM gold.dim_customers
GROUP BY gender
ORDER BY 2 DESC;

-- Find Total Product by category
SELECT 
	category, 
	COUNT(product_key) 'total_products'
FROM gold.dim_product
GROUP BY category
ORDER BY 2 DESC;

-- What is the average costs in each category
SELECT
	p.category, 
	AVG(product_cost) 'avg_price'
FROM gold.dim_product p
GROUP BY p.category
ORDER BY 2 DESC;

-- What is the total revenue generated for each category?
SELECT
	p.category, SUM(s.sales_amount) 'Total_Revenue'
FROM gold.dim_product p
RIGHT JOIN gold.fact_sales s
	ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY 2 DESC;

-- Find the Total Revenue generated by each customer?
SELECT
	C.customer_key, 
	C.first_name,
	c.last_name,
	SUM(s.sales_amount) 'Total_Revenue'
FROM gold.dim_customers C
RIGHT JOIN gold.fact_sales s
	ON C.customer_key = s.product_key
GROUP BY C.customer_key, C.first_name, c.last_name
ORDER BY 2 DESC;

-- What is the distribution of sold items across countries?
SELECT
	c.country, 
	SUM(s.quantity) 'total_sold_items'
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 2 DESC;


-----------------------------------------
-- RANKING ANALYSIS
-----------------------------------------
-- Which 5 products generate the highest revenue?
SELECT * 
FROM (
	SELECT
		p.product_name,
		SUM(s.sales_amount) AS total_revenue,
		RANK() OVER (ORDER BY SUM(sales_amount) DESC) AS ranking
	FROM gold.fact_sales s
	LEFT JOIN gold.dim_products p
		ON s.product_key = p.product_key
	GROUP BY p.product_name
) AS ranked_products
WHERE ranking <= 5;

-- What are the 5 worst-perfroming products in terms of sales?
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.product_key = c.customer_key
GROUP BY 
	c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(f.order_number) AS order_count
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key, c.first_name, c.last_name
ORDER BY order_count ASC;
